In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',None)


In [21]:
#load the library and check its version, just to make sure we aren't using an older version
import numpy as np
np.__version__
'1.12.1'

'1.12.1'

In [22]:
#create a list comprising numbers from 0 to 9
L = list(range(10))

In [23]:
#converting integers to string - this style of handling lists is known as list comprehension.
#List comprehension offers a versatile way to handle list manipulations tasks easily. We'll learn about them in future tutorials. Here's an example.  

[str(c) for c in L]
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

[type(item) for item in L]
[int, int, int, int, int, int, int, int, int, int]

[int, int, int, int, int, int, int, int, int, int]

In [24]:
a = [str(c) for c in L]


In [25]:
[type(item) for item in L]


[int, int, int, int, int, int, int, int, int, int]

In [26]:
a

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [27]:
[type(item) for item in a]

[str, str, str, str, str, str, str, str, str, str]

In [28]:
#ARRAY

In [29]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array


In [30]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

('x3 ndim: ', 3)
('x3 shape:', (3L, 4L, 5L))
('x3 size: ', 60)


In [31]:
print("dtype:", x3.dtype)


('dtype:', dtype('int32'))


In [32]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")


('itemsize:', 4, 'bytes')
('nbytes:', 240, 'bytes')


In [33]:
#Array Indexing: Accessing Single Elements¶


In [34]:
x1

array([5, 0, 3, 3, 7, 9])

In [35]:
x1[0]

5

In [36]:
x1[-1]

9

In [37]:
x1[-2]

7

In [38]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [39]:
x2[2, -1]

7

In [40]:
#Keep in mind that, unlike Python lists, NumPy arrays have a fixed type

In [41]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

In [42]:
##Array Slicing: Accessing Subarrays¶

In [43]:
# x[start:stop:step]
# default to the values start=0, stop=size of dimension, step=1

In [44]:
## one dimentional subarrays
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [46]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [47]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [48]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [49]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [50]:
# A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [51]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [52]:
## Multi-dimensional subarrays¶

In [53]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [54]:
x2[:2, :3]  # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [55]:
x2[:3, ::2]  # all rows, every other column 

array([[3, 2],
       [7, 8],
       [1, 7]])

In [56]:
x2[:3, -2::]  # all rows, last two columns

array([[2, 4],
       [8, 8],
       [7, 7]])

In [57]:
## Accessing array rows and columns¶

In [58]:
#One commonly needed routine is accessing of single rows or columns of an array. 
#This can be done by combining indexing and slicing, using an empty slice marked by a single colon (:):

In [59]:
print(x2[:, 0])  # first column of x2

[3 7 1]


In [60]:
print(x2[0, :])  # first row of x2

[3 5 2 4]


In [61]:
#In the case of row access, the empty slice can be omitted for a more compact syntax:

In [62]:
print(x2[0])  # equivalent to x2[0, :]

[3 5 2 4]


In [63]:
#Creating copies of arrays¶

In [64]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[3 5]
 [7 6]]


In [65]:
##Reshaping of Arrays

In [66]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
#Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. 
#This can be done with the reshape method, 
#or more easily done by making use of the newaxis keyword within a slice operation

In [68]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [69]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [70]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [71]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [72]:
##Array Concatenation and Splitting¶

In [73]:
#Concatenation of arrays
#accomplished using the routines np.concatenate, np.vstack, and np.hstack

In [74]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [75]:
#It can also be used for two-dimensional arrays:


In [76]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [77]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [78]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [79]:
#For arrays of mixed dimensions, use np.vstack (vertical stack) and np.hstack (horizontal stack) functions

In [80]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [81]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [82]:
#Splitting of arrays
#implemented by the functions np.split, np.hsplit, and np.vsplit

In [83]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))


In [84]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [86]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [88]:
#source: PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays